LineLength:
  Enabled: true
  Max: 180

MethodLength:
  Enabled: true
  Max: 100

Style/ClassLength:
  Exclude:
    # Most modules are quite large and all contained in one class.  This is OK.
    - 'modules/**/*'

Style/NumericLiterals:
  Enabled: false

Documentation:
  Exclude:
    - 'modules/**/*'
